db:
  name: dbname
  user: dev
  password: 123456
  port: 3306
  host: 127.0.0.1
  charset: utf8
  params: ?multiStatements=true&parseTime=true

# DEBUG
# INFO
# WARN
# ERROR
# DPANIC
# PANIC
# FATAL
logger:
  level: DEBUG

server:
  port: 8080
